[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
book = "B6FGFq5WVExospwD6XE4RiPdtjLp6R5wFRMYQeVPQsfz"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
post_build = "mkdir -p ../shared/idls && cp target/idl/book.json ../shared/idls/"
[hooks]
