[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
book = "BGd96f97JcSz84HJxcjyWY9ZnQismb69XWr9eNENEMoS"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"


