[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
book = { address="AQG2ZMQuQYSaSjxJwmsqQsASWChXwkTza2BRxKqBwHoC",path="../target/deploy/book.so"}

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
post_build = "mkdir -p ../shared/idls && cp target/idl/book.json ../shared/idls/"
test = "cargo test"

[hooks]
